services:
  ui:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/ui
    container_name: ui
    privileged: true
    ports:
    - 8501
    - 1111
    command:
    - streamlit
    - run
    - ui.py
    - --server.port=8501
    - --server.address=0.0.0.0
    networks:
      vlan1:
        ipv4_address: 192.168.0.2
  hmi:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/hmi
    container_name: hmi
    privileged: true
    command:
    - python3
    - -u
    - hmi.py
    volumes: []
    networks:
      vlan1:
        ipv4_address: 192.168.0.30
    ports:
    - 1111
    - 5020
  ats_plc:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/ats_plc
    container_name: ats_plc
    privileged: true
    command:
    - python3
    - -u
    - plc.py
    volumes:
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS1:/src/ttyS1
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS3:/src/ttyS3
    networks:
      vlan1:
        ipv4_address: 192.168.0.20
    ports:
    - 1111
    - 5020
  solar_panel_power_meter:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/solar_panel_power_meter
    container_name: solar_panel_power_meter
    privileged: true
    volumes:
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/physical_interations.db:/src/physical_interations.db
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS2:/src/ttyS2
    command:
    - python3
    - -u
    - sensor.py
    networks:
      vlan1:
        ipv4_address: 192.168.0.10
    ports:
    - 1111
    - 5020
  transfer_switch:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/transfer_switch
    container_name: transfer_switch
    privileged: true
    volumes:
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/physical_interations.db:/src/physical_interations.db
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS4:/src/ttyS4
    command:
    - python3
    - -u
    - actuator.py
    networks:
      vlan1:
        ipv4_address: 192.168.0.11
    ports:
    - 1111
    - 5020
  electrical_hil:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/electrical_hil
    container_name: electrical_hil
    privileged: true
    volumes:
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/physical_interations.db:/src/physical_interations.db
    command:
    - python3
    - -u
    - hil.py
networks:
  vlan1:
    driver: bridge
    name: ics_simlab
    ipam:
      config:
      - subnet: 192.168.0.0/24
    driver_opts:
      com.docker.network.bridge.name: ics_simlab
