services:
  ui:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/ui
    container_name: ui
    privileged: true
    ports:
    - 8501
    - 1111
    command:
    - streamlit
    - run
    - ui.py
    - --server.port=8501
    - --server.address=0.0.0.0
    networks:
      vlan1:
        ipv4_address: 192.168.0.111
  plc1:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/plc1
    container_name: plc1
    privileged: true
    command:
    - python3
    - -u
    - plc.py
    volumes:
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS1:/src/ttyS1
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS3:/src/ttyS3
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS5:/src/ttyS5
    networks:
      vlan1:
        ipv4_address: 192.168.0.21
    ports:
    - 1111
    - 5020
  tank_level_sensor:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/tank_level_sensor
    container_name: tank_level_sensor
    privileged: true
    volumes:
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/physical_interations.db:/src/physical_interations.db
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS2:/src/ttyS2
    command:
    - python3
    - -u
    - sensor.py
    networks:
      vlan1:
        ipv4_address: 192.168.0.11
    ports:
    - 1111
    - 5020
  tank_input_valve:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/tank_input_valve
    container_name: tank_input_valve
    privileged: true
    volumes:
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/physical_interations.db:/src/physical_interations.db
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS4:/src/ttyS4
    command:
    - python3
    - -u
    - actuator.py
    networks:
      vlan1:
        ipv4_address: 192.168.0.12
    ports:
    - 1111
    - 5020
  tank_output_valve:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/tank_output_valve
    container_name: tank_output_valve
    privileged: true
    volumes:
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/physical_interations.db:/src/physical_interations.db
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/ttyS6:/src/ttyS6
    command:
    - python3
    - -u
    - actuator.py
    networks:
      vlan1:
        ipv4_address: 192.168.0.13
    ports:
    - 1111
    - 5020
  bottle_factory:
    build: /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/containers/bottle_factory
    container_name: bottle_factory
    privileged: true
    volumes:
    - /home/jaxson/Documents/IndustrialControlSystems/ICS-SimLab/simulation/communications/physical_interations.db:/src/physical_interations.db
    command:
    - python3
    - -u
    - hil.py
networks:
  vlan1:
    driver: bridge
    name: bottle_factory
    ipam:
      config:
      - subnet: 192.168.0.0/24
    driver_opts:
      com.docker.network.bridge.name: bottle_factory
