services:
  plc1:
    build: containers/plc1
    container_name: plc1
    privileged: true
    networks:
      vlan1:
        ipv4_address: 192.168.0.21
  plc2:
    build: containers/plc2
    container_name: plc2
    privileged: true
    networks:
      vlan1:
        ipv4_address: 192.168.0.22
networks:
  networks:
    vlan1:
      driver: bridge
      name: ics_simlab
      ipam:
        config:
        - subnet: 192.168.0.0/24
      driver_opts:
        com.docker.network.bridge.name: ics_simlab
